spring:
  application:
    name: dubbo-order-consumer
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true


logging:
  config: classpath:logback-spring.xml
